export { default as authRoutes } from './auth.routes'
export { default as postRoutes } from './post.routes'
export { default as profileRoutes } from './profile.routes'
export { default as dashboardRoutes } from './dashboard.routes'
export {default as quoteRoutes} from './quote.routes'
export {default as commentRoutes} from './interactionsRoutes/comment.routes'
