export  { default as Home} from './Home'
export  { default as SignIn} from './SignIn'
export  { default as SignUp} from './SignUp'
export  { default as CreatePost} from './CreatePost'
export { default as ProfileSetup } from './ProfileSetup'
export { default as UpdateProfile } from './UpdateProfile'
export {default as Dashboard} from './Dashboard'